common:

production:

development:
  files_path: '/Users/hornairs/Sites/files/files'
  asset_host: 'http://localhost/files/files'

test:
  files_path: '/Users/hornairs/Sites/files/spec/fixtures/files'
