#embed_assets: on

template_extension: 'bars'
template_namespace: 'LDB.ViewRenderers'
template_function: 'LDB.renderTemplate'

javascripts:
  main:
    - public/javascripts/jquery/jquery.js
    - public/lib/jqueryui/ui/jquery.ui.core.js
    - public/lib/jqueryui/ui/jquery.ui.widget.js
    - public/lib/jqueryui/ui/jquery.ui.mouse.js
    - public/lib/jqueryui/ui/jquery.ui.*.js
    - public/lib/jqueryui/ui/jquery.effects.core.js
    - public/lib/jqueryui/ui/jquery.effects.*.js
    - public/lib/slickgrid/lib/jquery.event.drag-2.0.min.js
    - public/lib/slickgrid/slick.core.js
    - public/lib/slickgrid/slick.grid.js
    - public/lib/slickgrid/slick.editors.js
    - public/lib/underscore/underscore.js
    - public/lib/backbone/backbone.js
    - public/javascripts/bootstrap.js
    - client_app/views/**/*.bars

stylesheets:
  screen:
    - public/stylesheets/screen.css
    - public/stylesheets/aristo.jquery-ui.custom.css
    - public/lib/slickgrid/slick.grid.css
  print:
    - public/stylesheets/print.css
  ie:
    - public/stylesheets/ie.css

