#embed_assets: on

template_extension: 'bars'
template_namespace: 'FDB.ViewRenderers'
template_function: 'FDB.renderTemplate'

javascripts:
  main:
    - public/lib/jquery.js
    - public/lib/jqueryui/ui/jquery.ui.core.js
    - public/lib/jqueryui/ui/jquery.ui.widget.js
    - public/lib/jqueryui/ui/jquery.ui.mouse.js
    - public/lib/jqueryui/ui/jquery.ui.tabs.js
    - public/lib/jqueryui/ui/jquery.ui.datepicker.js
    - public/lib/jqueryui/ui/jquery.ui.button.js
    #- public/lib/jqueryui/ui/jquery.ui.*.js
    #- public/lib/jqueryui/ui/jquery.effects.core.js
    #- public/lib/jqueryui/ui/jquery.effects.*.js
    - public/lib/jquery.timePicker.js
    - public/lib/jquery.editable.js
    - public/lib/uniform/jquery.uniform.js
    - public/lib/slickgrid/lib/jquery.event.drag-2.0.min.js
    - public/lib/slickgrid/slick.core.js
    - public/lib/slickgrid/slick.grid.js
    - public/lib/slickgrid/slick.editors.js
    - public/lib/slickgrid/slick.dataview.js
    - public/lib/achtung/src/ui.achtung.js
    - public/lib/underscore/underscore.js
    - public/lib/backbone/backbone.js
    - public/lib/handlebars/handlebars.js
    - public/lib/inflections.js
    - public/javascripts/views.js
    - public/javascripts/forms.js
    - client_app/views/**/*.bars
    - public/javascripts/views/**/*.js
    - public/javascripts/models/**/*.js
    - public/javascripts/controllers/**/*.js
    - public/javascripts/bootstrap.js

stylesheets:
  screen:
    - public/stylesheets/screen.css
    - public/stylesheets/aristo.jquery-ui.custom.css
    - public/stylesheets/uniform.aristo.css
    - public/lib/slickgrid/slick.grid.css
    - public/lib/achtung/src/ui.achtung.css
  print:
    - public/stylesheets/print.css
  ie:
    - public/stylesheets/ie.css
