#embed_assets: on

javascripts:
  main:
    - public/javascripts/jquery/jquery.js
    - public/javascripts/underscore/underscore.js
    - public/javascripts/backbone/backbone.js
    - public/lib/jqueryui/ui/jquery.ui.core.js
    - public/lib/jqueryui/ui/jquery.ui.widget.js
    - public/lib/jqueryui/ui/jquery.ui.mouse.js
    - public/lib/jqueryui/ui/jquery.ui.*.js
    - public/lib/jqueryui/ui/jquery.effects.core.js
    - public/lib/jqueryui/ui/jquery.effects.*.js
    - public/lib/slickgrid/lib/jquery.event.drag-2.0.min.js
    - public/lib/slickgrid/slick.core.js
    - public/lib/slickgrid/slick.grid.js
    - public/lib/slickgrid/slick.editors.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  screen:
    - public/stylesheets/screen.css
    - public/stylesheets/aristo.jquery-ui.custom.css
    - public/lib/slickgrid/slick.grid.css
  print:
    - public/stylesheets/print.css
  ie:
    - public/stylesheets/ie.css

